### ISSUE TITLE
Support for mutation-testing-elements

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-dashboard#105]
Time for the next step: hosting mutation testing reports. We will use [mutation-testing-elements](https://github.com/stryker-mutator/mutation-testing-elements) for the json schema as well as the html report itself.

Suggestion for the new api:

`HTTP POST https://dashboard.stryker-mutator.io/api/reports`

```json
{
  "apiKey": "61213121e3wdasdASD",
  "branch": "master",
  "mutationScore": 80,
  "repositorySlug": "github.com/stryker-mutator/stryker",
  "report": { "...": "..." }
}
```

**Comment by nicojs** [comment]
Apparently `Label` isn't supported yet by the stryker dashboard. Removing it from my example

**Comment by simondel** [comment]
We decided to do this with blob storage.

**Comment by nicojs** [comment]
Duplicate of #108
