### ISSUE TITLE
Non-existant repositorySlug should return a 404 Not Found

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker-dashboard#113]
When the repositorySlug does not exist such as by not prepending `github.com/` to it (https://github.com/stryker-mutator/stryker4s/issues/221) the dashboard reporter returns a 200 with a body of `null` (string). This is not very useful. If the dashboard were to return a 404, possibly with a message that the repositorySlug is not found, it would be clearer what went wrong

**Comment by hugo-vrijswijk** [comment]
Fixed in the new dashboard

**Comment by nicojs** [comment]
Yep, true.
