### ISSUE TITLE
Badge redirect is mangled

### ISSUE THREAD

**Issue by Bilge** [stryker-mutator/stryker-dashboard#126]
* Visit `https://badge.stryker-mutator.io/github.com/my/repo/5.0` [go⬈](https://badge.stryker-mutator.io/github.com/my/repo/5.0)
* Redirects to `https://img.shields.io/endpoint?url=https%3A%2F%2Fbadge-api.stryker-mutator.io%2Fgithub.com%2Fmy%2Frepo%2F5`

Notice the branch name has been truncated from `5.0` -> `5`. Seems something is interpreting the path component as a number and simplifying it from a float to an int. Nasty.

**Comment by nicojs** [comment]
Hi @Bilge thanks for reporting, I will have a look.

In the meantime, please use the new url scheme (letting shields.io serve the image).
