### ISSUE TITLE
Some badges working, some badges not

### ISSUE THREAD

**Issue by CJDennis** [stryker-mutator/stryker-dashboard#135]
* Working:
  * ![Infection MSI](https://badge.stryker-mutator.io/github.com/CJDennis/hidden-value/master) https://github.com/CJDennis/hidden-value
  * ![Infection MSI](https://badge.stryker-mutator.io/github.com/CJDennis/rounding/master) https://github.com/CJDennis/rounding
* Not working:
  * ![Infection MSI](https://badge.stryker-mutator.io/github.com/CJDennis/mac-address/master) https://github.com/CJDennis/mac-address
  * ![Infection MSI](https://badge.stryker-mutator.io/github.com/CJDennis/unit-test-compatibility/master) https://github.com/CJDennis/unit-test-compatibility

Plus more examples of each.

Why are some working and some not? I've set up each one the same way with its own key as I've activated it from the Stryker dashboard.

**Comment by nicojs** [comment]
Hi @CJDennis 👋 thanks for reporting this issue.

I've looked in the database, but I can't find reports for `unit-test-compatibility` or `mac-address`. I can find the repositories, and I can see you've enabled them. Can you please confirm that you've uploaded a report?

Nice scores for hidden-value and rounding 👍
