### ISSUE TITLE
Version does not accept "."

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-dashboard#138]
When the version string does contain a "." the resulting report url does not work. 

Example:
https://dashboard.stryker-mutator.io/reports/github.com/richardwerkman/stryker-net/my.test

It could be that the . causes the path to look like a file.

https://github.com/stryker-mutator/stryker-dashboard/blob/3369498044517a3fc0893831b499f778df6c03dd/packages/website-backend/src/middleware/spaMiddleware.ts#L13

**Comment by nicojs** [comment]
Good catch!

**Comment by nicojs** [comment]
I had some spare time. Fixed and released in v0.5.1 of the dashboard.
