### ISSUE TITLE
Too many privileges

### ISSUE THREAD

**Issue by nicojs** [stryker-mutator/stryker-dashboard#142]
We're requesting too many privileges. We shouldn't need "commit" access.

![image](https://user-images.githubusercontent.com/1828233/71531042-2ddc6480-28ed-11ea-9ccf-563397010188.png)

See also:
https://twitter.com/tfidry/status/1210651591918997508

**Comment by mthmulders** [comment]
I vaguely remember having seen a similar issues earlier... #95 and #96 also reported too broad permissions. Maybe we should start with again, with an empty list and just adding permissions as they are really needed, instead of going for the convenient approach?

**Comment by ptoonen** [comment]
Browsing the code I see that it specifically checks for 'push' access - isn't this a way to verify that someone creating the dashboard account/report actually has ownership of the repo/org they're trying to create the report for?

**Comment by nicojs** [comment]
It seems that we are requesting too many scopes here: 
https://github.com/stryker-mutator/stryker-dashboard/blob/87fe0b1b56b62811ec99032c9d14a6497522a1d5/packages/website-backend/src/api/auth/GithubAuth.ts#L19-L20

**Comment by nicojs** [comment]
It seems that simply removing `'repo:status'` seems to work.
