### ISSUE TITLE
Improve UX for users with a large number of repos

### ISSUE THREAD

**Issue by brodycj** [stryker-mutator/stryker-dashboard#144]
https://dashboard.stryker-mutator.io/repos/brodybits - long scrollable list since I have over 400 forks

I think it would be nice for the UX to be more easily searchable and to keep enabled repos at the top.

I do keep a number of personal GitHub orgs to manage some of my work. I should probably clean up my forks and keep most of them in a personal GitHub org.

**Comment by simondel** [comment]
A search bar and a toggle to only show enabled repos sounds awesome :) Would you be willing to implement this?

**Comment by xandervedder** [comment]
Enabled and disabled repositories are now split, searching will be implemented in #891.
