### ISSUE TITLE
Dashboard a bit slow to load

### ISSUE THREAD

**Issue by theofidry** [stryker-mutator/stryker-dashboard#146]
See the screenshot bellow where I was switching from `infection` to `theofidry` back and forth.

<img width="512" alt="Screen Shot 2020-03-06 at 21 53 52" src="https://user-images.githubusercontent.com/5175937/76121902-1b6d5e00-5ff5-11ea-9bff-810d3f1d0486.png">

I think the result could be cached like in Travis with a default TTL and allow maybe an account page or button to force a new synchronization if ncessary.

**Comment by xandervedder** [comment]
Hi there, do you still experience this issue?

**Comment by xandervedder** [comment]
It's faster now, but we should show a loading spinner #890. I will close this for now, but there might still be performance improvements possible.
