### ISSUE TITLE
Sort repositories by type

### ISSUE THREAD

**Issue by theofidry** [stryker-mutator/stryker-dashboard#147]
Maybe a combination of both could be done:

- Adding a search
- Sort repositories by type and _then_ by name:
  - provider
  - repository enabled
  - source repository
  - fork

This would allow the list to be much more friendly when like me you have 152 repositories but only one enabled

**Comment by xandervedder** [comment]
This should partially have been fixed, as right now we split the enabled and disabled repositories. The searchbar will be done in #891.

We could potentially tackle a lot with the searchbar so I'm thinking sorting is not needed (but do tell if you disagree 👍)
