### ISSUE TITLE
Slow redirection

### ISSUE THREAD

**Issue by theofidry** [stryker-mutator/stryker-dashboard#148]
When I access to the dashboard logged in (e.g. `https://dashboard.stryker-mutator.io/repos/theofidry`) and click on the stryker icon top left, I get redirected to the following page:

<img width="1440" alt="Screen Shot 2020-03-06 at 22 02 05" src="https://user-images.githubusercontent.com/5175937/76122355-24126400-5ff6-11ea-9799-9836bc844907.png">

And then it takes a solid 1-2 seconds before redirecting me to `https://dashboard.stryker-mutator.io/repos/theofidry` because I'm logged in

**Comment by xandervedder** [comment]
This should be fixed.
