### ISSUE TITLE
Make the mutation ID's optionals

### ISSUE THREAD

**Issue by theofidry** [stryker-mutator/stryker-dashboard#154]
I don't think we should expect all mutation testing tools to provide the ability to track mutations. So with that in mind, maybe it would be worth to allow the ID to be optional and simply not show it when not available.

**Comment by xandervedder** [comment]
I don't think we show mutation IDs anymore, unless I am misunderstanding.

For the time being, I will close this since I don't think it's relevant anymore (do correct me if I am wrong).
