### ISSUE TITLE
Issue with shared xmldom org

### ISSUE THREAD

**Issue by brodybits** [stryker-mutator/stryker-dashboard#156]
I was hoping to add the xmldom project from the xmldom org (<https://github.com/xmldom>) but for some reason the dashboard does not seem to see xmldom as one of my orgs. I am one of 3 shared owners of this org.

Thanks in advance!

**Comment by brodybits** [comment]
I think the issue is that I have more orgs than the dashboard can handle, not all of my own orgs show up. I am running a fork of xmldom in my own xbrew org for now.

**Comment by karfau** [comment]
@brodybits when I go to https://github.com/settings/applications and click on the entry for Stryker, and grant it access to the xmldom org, and go back to the dashboard (https://dashboard.stryker-mutator.io/) I'm able to select the xmldom org and enable it.
Can you check that stryker has access in the settings?

**Comment by xandervedder** [comment]
I am assuming this has since been resolved, closing for that reason.

---
If this is still an issue, I will re-open this issue 😃.

**Comment by rouke-broersma** [comment]
> I am assuming this has since been resolved, closing for that reason.
> 
> ---
> If this is still an issue, I will re-open this issue 😃. 

Don't think this has been fixed tbh

**Comment by karfau** [comment]
For us it was resolved.
