### ISSUE TITLE
Stryker badge should have the word "report" in the label

### ISSUE THREAD

**Issue by brodybits** [stryker-mutator/stryker-dashboard#158]
I think it would still not be super-obvious to newcomers that the "Mutation score" badge would link to the nice, valuable HTML report on the Stryker dashboard.

**Comment by xandervedder** [comment]
@nicojs & @rouke-broersma, what do you think about this?

Personally I am fine with the way it is currently presented.

**Comment by rouke-broersma** [comment]
> @nicojs & @rouke-broersma, what do you think about this?
> 
> Personally I am fine with the way it is currently presented.

The point is that badges are not usually clickable, so it's not obvious that you can go from the badge to a nice report. I don't really know how to make that more obvious though. But the button text is user editable anyway since it simply uses shieldsio.

**Comment by xandervedder** [comment]
If the text is editable, I don't think this is an issue at all.

I would think if a user is really curious, they will click on the badge anyway.
