### ISSUE TITLE
[feature-request] Support storage other than Azure ?

### ISSUE THREAD

**Issue by Niceplace** [stryker-mutator/stryker-dashboard#176]
Hello ! 

I am wondering if there are plans to support  backends other than Azure Storage ?

We are considering using stryker-dashboard to store the result of mutation testing for our Typescript & Kotlin projects (report generated with pitest).
We would love to self-host a dashboard instance but we do not use Azure, we use AWS.

Cheers and thanks for a great product :) !

**Comment by rouke-broersma** [comment]
Not at this time.
