### ISSUE TITLE
Support HEAD branch

### ISSUE THREAD

**Issue by regseb** [stryker-mutator/stryker-dashboard#210]
I want to link to dashboard of the default branch of my project.

I was hoping to use `HEAD` ([https://badge-api.stryker-mutator.io/github.com/regseb/cronnor/**HEAD**](https://badge-api.stryker-mutator.io/github.com/regseb/cronnor/HEAD) or [https://dashboard.stryker-mutator.io/reports/github.com/regseb/cronnor/**HEAD**](https://dashboard.stryker-mutator.io/reports/github.com/regseb/cronnor/HEAD)), but it doesn't work. Is it possible to support `HEAD`?

I could use `master`, but if my default changes: I would have to change all links.

**Comment by nicojs** [comment]
The stryker-dashboard doesn't care the version, see https://stryker-mutator.io/docs/General/dashboard. Probably you need to configure your mutation testing framework to use "HEAD". Which framework are you using?

For StrykerJS: see https://stryker-mutator.io/docs/stryker-js/configuration#dashboard-dashboardoptions

**Comment by regseb** [comment]
I think my explanation was not clear enough (or I didn't understand the answer 😅).

When I link to a file in GitHub on the default branch, there are two solutions:

- The branch name: [https://github.com/stryker-mutator/stryker-dashboard/blob/**master**/README.md](https://github.com/stryker-mutator/stryker-dashboard/blob/master/README.md). But if the default branch is renamed: you have to change the link (eg. [https://github.com/stryker-mutator/stryker-dashboard/blob/**main**/README.md](https://github.com/stryker-mutator/stryker-dashboard/blob/main/README.md)).
- The pseudo-branch _HEAD_: [https://github.com/stryker-mutator/stryker-dashboard/blob/**HEAD**/README.md](https://github.com/stryker-mutator/stryker-dashboard/blob/HEAD/README.md). If the default branch changes, the link is still valid.

I would like to do the same thing for the stryker-dashboard links by replacing _master_ by _HEAD_:

```Markdown
[![Mutation testing badge](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fbadge-api.stryker-mutator.io%2Fgithub.com%2Fstryker-mutator%2Fstryker-dashboard%2Fmaster)](https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/stryker-dashboard/master)
                                                                                                                                                                          ^^^^^^                                                                                             ^^^^^^
[![Mutation testing badge](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fbadge-api.stryker-mutator.io%2Fgithub.com%2Fstryker-mutator%2Fstryker-dashboard%2FHEAD)](https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/stryker-dashboard/HEAD)
                                                                                                                                                                          ^^^^                                                                                             ^^^^
```

---

> Which framework are you using?

I use StrykerJS in a [GitHub Actions](https://github.com/regseb/cronnor/blob/20dca2057e7aa544710992bc0aa62af4bd571358/.github/workflows/ci.yml#L71-L74):

```YAML
    - name: Send coverage
      run: npm test
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
```

With this [configuration](https://github.com/regseb/cronnor/blob/20dca2057e7aa544710992bc0aa62af4bd571358/stryker.conf.json):

```JSON
{
    "commandRunner": { "command": "mocha" },
    "logLevel": "warn",
    "reporters": ["dots", "clear-text", "dashboard"]
}
```

**Comment by nicojs** [comment]
Again, the stryker-dashboard doesn't care about versions, but doesn't support a versionless url. The "default branch" isn't a git concept, so there is no git command or env variable you can use to determine the "default branch".

Also: HEAD in git is just the current branch you're on, so I don't think HEAD would be a great version identifier. 

However, feel free to use it. In StrykerJS you can use `--dashboard.version HEAD` to force Stryker to update the HEAD dashboard version.

**Comment by regseb** [comment]
Thanks for the answer which taught me some things about Git and GitHub. And I understood how stryker-dashboard works and my proposal doesn't make sense.

**Comment by nicojs** [comment]
Happy to help 👍
