### ISSUE TITLE
Consider replacing `unpkg` CDN

### ISSUE THREAD

**Issue by maks-rafalko** [stryker-mutator/stryker-dashboard#215]
Originally posted here https://github.com/infection/infection/issues/1646

The main idea is to replace `unpkg` with more reliable CDN

@nicojs suggest the following https://github.com/infection/infection/issues/1646#issuecomment-1013685979

> Yeah unpkg isn't the most reliable CDN out there. Might be time to switch over to a locally served one, or include it in the JS bundle.
> Feel free to open an issue at the dashboard GH repo

<details>

> **Is your feature request related to a problem? Please describe.** I just started using Infection and I noted that the generated HTML log includes [a call](https://github.com/infection/infection/search?q=https%3A%2F%2Fwww.unpkg.com%2Fmutation-testing-elements) to a remote resource:
> 
> ```
> <script defer src="https://www.unpkg.com/mutation-testing-elements"></script>
> ```
> 
> Unfortunately, this URL is not available 100% of the time and I'm getting constant timeout issues that restrict me from seeing the HTML logs.
> 
> **Describe the solution you'd like** I would like to be able to work with Infection without having to depend on a remotely hosted resource that could fail at any time.
> 
> **Describe alternatives you've considered** I believe that the `mutation-testing-elements` js should be included in local, otherwise host it in a more reliable place (GitHub pages?)
> 
> **Additional context** ![image](https://user-images.githubusercontent.com/20590102/149580407-bb7bc5bd-6f84-4db4-9af7-9915bd7a39a0.png)

</details>

**Comment by nicojs** [comment]
Which CDN would be better?

**Comment by maks-rafalko** [comment]
See https://github.com/infection/infection/issues/1646#issuecomment-1438883763

> Consider using https://www.jsdelivr.com/, its built for high availability. https://cdn.jsdelivr.net/npm/mutation-testing-elements@1.7.8/dist/mutation-test-elements.js
