### ISSUE TITLE
Badge API is not working

### ISSUE THREAD

**Issue by IonBazan** [stryker-mutator/stryker-dashboard#233]
I noticed some time ago that the `badge-api` service is not working (including the badge for this repository):

https://badge-api.stryker-mutator.io/github.com/stryker-mutator/stryker-dashboard/master produces `503: The service is unavailable.`:
![image](https://user-images.githubusercontent.com/1985514/169442515-456d5c8f-b7c5-42ad-8ea5-21a0741122f3.png)

**Comment by 1bberto** [comment]
seems to be working now
