### ISSUE TITLE
Cannot remove repository

### ISSUE THREAD

**Issue by simondel** [stryker-mutator/stryker-dashboard#34]
When I remove a repository, the switch on the dashboard goes to the 'off' position:
![afbeelding](https://user-images.githubusercontent.com/4221997/35766179-2f4330f6-08d3-11e8-94f7-54feb1907089.png)
However, when I refresh the page the repository is enabled again:
![afbeelding](https://user-images.githubusercontent.com/4221997/35766183-3fa0e25e-08d3-11e8-8251-c0a7e075b993.png)

When I looked in the storage explorer, I noticed that the API key has was succesfully removed, but the project was still enabled:
![afbeelding](https://user-images.githubusercontent.com/4221997/35766213-b25e47be-08d3-11e8-913f-c040b9194d65.png)

**Comment by simondel** [comment]
Perhaps it's this code:
https://github.com/stryker-mutator/stryker-badge/blob/a04e8be71f6678374bb5fc52c30e26e2efa34ce5/packages/website-backend/src/services/GithubRepositoryService.ts#L58-L61

It seems to always pass `enabled: true`

**Comment by nicojs** [comment]
Lol. It's time we enable `strict` mode as well as enable `noUnusedParameters` in tsconfig. This is the problem indeed.

**Comment by nicojs** [comment]
I think this one is fixed for some time.
