### ISSUE TITLE
Migrate `azure-storage` to `@azure/storage-blob` and `@azure/data-tables`

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-dashboard#375]
```
Please note: newer packages @azure/storage-blob, @azure/storage-queue and @azure/storage-file are available as of November 2019 and @azure/data-tables is available as of June 2021. 
While the legacy azure-storage package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Migration guide can be found: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/MigrationGuide.md
```

source: https://www.npmjs.com/package/azure-storage

---

Also make sure that we can use dependency injection.

**Comment by rouke-broersma** [comment]
Should also see if we can set blob removal time once we use the new libraries

**Comment by xandervedder** [comment]
Migration guide can be found here: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/MigrationGuide.md.

---

And good news, it appears that we can set an `expireOn` for blobs:
https://learn.microsoft.com/en-us/javascript/api/@azure/storage-blob/accesspolicy?view=azure-node-latest

I would propose something like 2-3 days to delete real-time blobs, these are short-lived and I hope a testrun is not longer than 3 days...

**Comment by xandervedder** [comment]
Cannot continue implementing until https://github.com/Azure/azure-sdk-for-js/issues/27813 is fixed.

**Comment by xandervedder** [comment]
The issue mentioned is fixed, I'll try to see if we can migrate now.
