### ISSUE TITLE
Give the dashboard a fresh coat of paint

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-dashboard#385]
The dashboard currently looks a bit outdated and could use a refresher.

The following needs to be updated:
1. Styling (need a design first).
2. Better UX:
   a. #144.
   b. #147
   c. #148 (not slow anymore, but it isn't nice visually what happens on the page).
3. Better onboarding.
   a. #149 (we could show strykers' reports as an example).
   
---

**Ideas:**
* Trends: History of mutation score.
* Discoverability: able to see different reports from the main page.
* Report summaries. Where are most mutants located?

**Comment by nicojs** [comment]
- Add statistics: 
   - "x projects onboarded"
   - "Average mutation score is X"
   - "A list of top repositories"

**Comment by lex-funy** [comment]
The ability to pin certain repositories to the top of the webpage might be useful.

**Comment by JortWillemsen** [comment]
First drafts of the redesigned dashboard. Thanks to some input from @xandervedder.

![Schermafbeelding 2023-10-07 171724](https://github.com/stryker-mutator/stryker-dashboard/assets/32990828/8b38d6c9-41a4-48bb-841d-0f52f6eaf586)
- The homepage now really is a home page and follows the same philosophy as the main [Stryker site](http://stryker-mutator.io)
- Getting started is clearly visible and conveys to the user what dashboard actually does.
- We need some good suggestions for a tag line that clearly describes what dashboard entails. 
- In the view your results section we could add some graphs, trends and reports from one of the stryker repositories to convey the result when using dashboard.

![Schermafbeelding 2023-10-07 171656](https://github.com/stryker-mutator/stryker-dashboard/assets/32990828/acc2947d-3b45-479a-8b12-134693b703f3)
- topbar is now in line with the stryker website (should ease the transition between the websites and make it feel more first party)
- Only the repositories that use dashboard are now visible (declutters the view).
- Personal repositories are at the top
- Organisation repositories are clearly grouped
- Mutation score is clearly visible
- Enable repository button now exists at the top right. Here you can enable a repository for dashboard.
- View button redirects to the page for the report, trends and insights.

**Comment by xandervedder** [comment]
We could also add documentation for the API somewhere as a separate page (like Swagger). Not sure if it’s difficult to theme a swagger page with Stryker colors..

**Comment by JortWillemsen** [comment]
![dashboard_repository](https://github.com/stryker-mutator/stryker-dashboard/assets/32990828/cc85ce3c-f822-4298-b87a-4b84ec043708)
![dashboard_home – 1](https://github.com/stryker-mutator/stryker-dashboard/assets/32990828/eaca9d8f-99aa-4729-b6cc-9b0fe6fe97ef)
![dashboard_home](https://github.com/stryker-mutator/stryker-dashboard/assets/32990828/aafd4c82-36af-489e-93b4-6eda405df6c3)


Updated designs :D

**Comment by JortWillemsen** [comment]
https://github.com/JortWillemsen/stryker-dashboard-redesign

This is the fork that we can work in.

**Comment by xandervedder** [comment]
I will close this issue, as I'm making new issues for the comparing and history functionality:

https://www.figma.com/design/yW9Q5nb7KYGv4e6JsKc6kD/Stryker-dashboard-current?node-id=64-25&node-type=canvas
