### ISSUE TITLE
feat: apply atomic design to components

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-dashboard#394]
https://bradfrost.com/blog/post/atomic-web-design/

---

Issue taken from https://github.com/JortWillemsen/stryker-dashboard-redesign/issues/23

**Comment by xandervedder** [comment]
In this case it makes sense to only use the following:
1. Atoms
2. Molecules
3. Organisms

To me it doesn't make sense for the `stryker-elements` library to include more than that. Would you agree @jensk-dev?

**Comment by jensk-dev** [comment]
Yes, I'd agree that any components more specifically tailored to a specific domain should be included in said domain
