### ISSUE TITLE
chore: remaining PR comments

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-dashboard#397]
See https://github.com/stryker-mutator/stryker-dashboard/pull/392.

**Comment by xandervedder** [comment]
@JairJosafath Would you like to pick this up?

1. https://github.com/stryker-mutator/stryker-dashboard/pull/392#discussion_r1365748914
2. https://github.com/stryker-mutator/stryker-dashboard/pull/392#discussion_r1365776552
3. https://github.com/stryker-mutator/stryker-dashboard/pull/392#issuecomment-1767929305
4. https://github.com/stryker-mutator/stryker-dashboard/pull/392#discussion_r1363453017
5. https://github.com/stryker-mutator/stryker-dashboard/pull/392#discussion_r1363457077
6. ... and more 😃

**Comment by JairJosafath** [comment]
> @JairJosafath Would you like to pick this up?
> 
> 1. https://github.com/stryker-mutator/stryker-dashboard/pull/392#discussion_r1365748914
> 2. https://github.com/stryker-mutator/stryker-dashboard/pull/392#discussion_r1365776552
> 3. https://github.com/stryker-mutator/stryker-dashboard/pull/392#issuecomment-1767929305
> 4. https://github.com/stryker-mutator/stryker-dashboard/pull/392#discussion_r1363453017
> 5. https://github.com/stryker-mutator/stryker-dashboard/pull/392#discussion_r1363457077
> 6. ... and more 😃 

@xandervedder yessr, I have time on the weekends, if I have questions I'll ask you.

I couldn't quite find the guidelines on how to contribute. contributing to open source is still a bit uncharted territory for me LOL.

**Comment by xandervedder** [comment]
No worries! These comments (in the linked PR) are pretty simple, so it seemed like a good idea to me for you to pick them up 🙂.

We have contributing guidelines (which are strangely not in this repository or I cannot find it...):
https://github.com/stryker-mutator/stryker-js/blob/master/CONTRIBUTING.md (which also applies to this project).

---

I suggest to try to fix some of the comments in the linked PR, create a branch (i.e. `fix/remaining-pr-comments` or something like that), push it, create a pull request and I will review it. If you don't understand something you can tag me in that comment, I will help you (if I have time).

**Comment by JairJosafath** [comment]
awesome
