### ISSUE TITLE
feat: new repositories page

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-dashboard#398]
Related: https://github.com/stryker-mutator/stryker-dashboard/issues/385.

**Comment by hugo-vrijswijk** [comment]
Some ideas:

- When going to the page for the first time, it looks like you get an error telling you to click "Enable repositories" button, which doesn't exist
- API key should have some info about how to use it and configure it
- List of "Disabled" repositories should be shown _below_ the "Enabled" repositories
  - _Or_: There should be a list of "Enabled" and "All", where "All" is similar to the current page
- Badge popup should have info about how to use and configure it (And button should be "Copy markdown")

**Comment by xandervedder** [comment]
This has been implemented and is on production now 🙂.
