### ISSUE TITLE
feat(homepage): add supported frameworks to the homepage

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-dashboard#402]
I'd like to see a list of all supported mutation test frameworks that work with the stryker dashboard. Maybe in a carousel so we can add new supported frameworks easily later.

Potential useful snippet: https://bbbootstrap.com/snippets/clients-brand-logo-carousel-slider-20683486

**Comment by maks-rafalko** [comment]
> @maks-rafalko Hi there, could we add Infection to this? 😃 

Hello, sure! Infection perfectly works with Stryker Dasboard. Thank you 👍
