### ISSUE TITLE
Support gzip Content-Encoding

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker-dashboard#523]
[Nest.JS supports compression](https://docs.nestjs.com/techniques/compression), but they suggest not enabling it in the app, but in the application server. Not sure if this is something that can be enabled easily in the Azure portal, but it is worth looking into

<img width="579" alt="image" src="https://github.com/stryker-mutator/stryker-dashboard/assets/10114577/0f340ce2-d76f-4998-8196-923315d82b70">

For larger reports there are even bigger benefits

**Comment by xandervedder** [comment]
By the way @hugo-vrijswijk, would you mind using milestones for future issues/releases?

I like organizing issues this way, curious to know what you think about this 😃.

**Comment by hugo-vrijswijk** [comment]
Yes, of course! I've never used milestones before, but I suppose it makes it easy to plan when to release. It might be useful to add something about it in the contributing.md?
