### ISSUE TITLE
Improve E2E test configuration

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-dashboard#550]
Right now, without modifying the code, it is impossible for contributers to run e2e tests. The reason for this, is because we use https://github.com/strykermutator-test-account for running these tests.

It should be possible to run these test by configuring a user. This poses some challenges as I see that these tests are highly specific (and probably should be generalized).

**Comment by xandervedder** [comment]
To add, the current steps to run the e2e tests are as follows (and these should also be documented):

1. Run website-backend and website-frontend.
2. Make sure there is an `.env` file which includes all variables.
    a. To obtain the E2E_ACCESS_TOKEN, you would need to log in as `stryker-mutator-test-account` locally.
    b. After logging in, copy the authToken from the session storage.
    c. Decode the JWT-token, copy the accessToken property and paste it in the `.env` file.

More is probably required to run the e2e for the badge-api.

**Comment by hugo-vrijswijk** [comment]
Might be a separate issue, but external contributors can't run e2e tests in CI: https://github.com/stryker-mutator/stryker-dashboard/actions/runs/8323453511/job/22773317305

**Comment by xandervedder** [comment]
That’s a separate issue indeed, because forks cannot access tokens we specify in this repository lerna cannot publish to npm 😃. 

I will also make an issue that improves our workflows.

**Comment by xandervedder** [comment]
Another problem spotted with our new configuration (nx upgrade): the launch config in the `launch.json` inside the `e2e` package no longer works. This is because our `node_modules` are symlinked now (to the root `node_modules`), which vscode doesn't really like. Directly linking to the root `node_modules` does not seem to work either. I will have to manually run it now which is also kind of cumbersome. So we should definitely improve that too.

**Comment by xandervedder** [comment]
@hugo-vrijswijk off topic, but can you release a new version of the dashboard? After the lerna changes I am not sure how this should be done...

I know this isn't the right place, but it is the fastest way of reaching out 😅.

**Comment by hugo-vrijswijk** [comment]
> @hugo-vrijswijk off topic, but can you release a new version of the dashboard? After the lerna changes I am not sure how this should be done...
> 
> I know this isn't the right place, but it is the fastest way of reaching out 😅.

Releasing is as simple as running `npx lerna version:minor`. Same as in [mutation-testing-elements](https://github.com/stryker-mutator/mutation-testing-elements/?tab=readme-ov-file#releasing). 

But are you sure you want to release the current version of the repositories page? I love the new styling, but I would say it needs a bit more polish. There's no "steps" when activating a repository that tell the user what to do. Just a uuid. There's also no links to the docs, or a way to create a new key

**Comment by xandervedder** [comment]
> Releasing is as simple as running GH_TOKEN=$(gh auth token) && npx lerna version minor. Same as in [mutation-testing-elements](https://github.com/stryker-mutator/mutation-testing-elements/?tab=readme-ov-file#releasing).

Alright, thanks!

> But are you sure you want to release the current version of the repositories page? I love the new styling, but I would say it needs a bit more polish. There's no "steps" when activating a repository that tell the user what to do. Just a uuid. There's also no links to the docs, or a way to create a new key

Hmm yes, it is missing some polish. Good idea, I will probably fix those smaller issues on Friday 😃
