### ISSUE TITLE
Realtime report does not work due to compression

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-dashboard#592]
![image](https://github.com/stryker-mutator/stryker-dashboard/assets/34238405/0c2ec7a7-1d97-4d45-961a-874eceb6f52a)

@hugo-vrijswijk you changed something with the CSP a while ago, did this get released (or was this a fix for this)?

**Comment by xandervedder** [comment]
potentially something missing here https://github.com/stryker-mutator/stryker-dashboard/blob/08ae65d77108808889c8cd44d15dada057901c68/packages/website-backend/src/index.ts#L58

**Comment by hugo-vrijswijk** [comment]
Oops, yeah this is from my changes. I didn't test the real-time report. Though I don't understand what particular part of the real-time report uses eval.

**Comment by xandervedder** [comment]
I am not sure too why this happened, it could be that by building the mutation testing elements, it includes eval somehow? I have seen it before when building angular for production, might be worth to also look at that.

**Comment by xandervedder** [comment]
I just used a different browser where the issue is not present (perhaps it is one of my extensions..?), but real-time reporting did not work anymore. I am thinking it has to do with this PR: https://github.com/stryker-mutator/stryker-dashboard/pull/524

I'm hoping I will have a fix for this soon

**Comment by xandervedder** [comment]
Hmm, I did another test with curl: (https://stryker-dashboard-acceptance.azurewebsites.net/api/real-time/github.com/xandervedder/Wrappit/main?realTime=true) and it showed me the events. I will roll out your change once again.. 😅

**Comment by hugo-vrijswijk** [comment]
Curl does not do CSP checks, so that makes sense

**Comment by hugo-vrijswijk** [comment]
I did some tests using [git bisect](https://git-scm.com/docs/git-bisect) and the offending PR is #533

**Comment by xandervedder** [comment]
Perhaps we could disable compression for all real-time endpoints?

It does make sense compression would break SSE 😮
