### ISSUE TITLE
Replace mock report on home page with StrykerJS report

### ISSUE THREAD

**Issue by lex-funy** [stryker-mutator/stryker-dashboard#594]
The mock repository at the bottom of the home page should be changed to match an actual repository. For example StrykerJS.

![image](https://github.com/stryker-mutator/stryker-dashboard/assets/7807951/f94b3047-b9c9-48b2-bb9d-4afa36e72ffb)

StrykerJS Report: https://dashboard.stryker-mutator.io/reports/github.com/stryker-mutator/stryker-js/master#mutant

**Comment by xandervedder** [comment]
Changed it with Stryker.NET. Though it's not a progress bar (that will change, soon).
