### ISSUE TITLE
When loading takes longer than `x` amount, show spinner

### ISSUE THREAD

**Issue by xandervedder** [stryker-mutator/stryker-dashboard#890]
Currently, we have the `sme-loader` component, which fades the content in smoothly when it finished loading. When loading takes a long time, we will see 'no' content for a while, which might not be good for the user experience. 

To fix this, we could introduce a spinner that spins until it is done (indicating longer loading times).

**Comment by xandervedder** [comment]
@lex-funy would you like to pick this up? Seems like a good small feature, I can give you pointers if you want 😃.

**Comment by hugo-vrijswijk** [comment]
I think the two places where this is most noticable is the repos page (when loading all repositories) and a report page (when loading the report json for a big repo)

**Comment by xandervedder** [comment]
I had some cool ideas, like the visor spinning in circles (or even the stryker logo itself).
