### ISSUE TITLE
expired certificate

### ISSUE THREAD

**Issue by gkueny** [stryker-mutator/stryker-dashboard#93]
https://dashboard.stryker-mutator.io/ certificate has expired today : Expired Thursday, May 3, 2018 at 16:35:17 Central European Time (translate from french)

**Comment by ptoonen** [comment]
We’re working on it!

**Comment by nicojs** [comment]
Thanks @gkueny ! Certificate fixed. Will be automated next time 😓

**Comment by ptoonen** [comment]
The issue occurred due to automation failure + not all having access to the DNS settings for the domain. We'll get this sorted. Sorry for the inconvenience!

**Comment by nicojs** [comment]
Also: a car accident of one of our key players 🚗

**Comment by dmitriytat** [comment]
It repeated again

**Comment by simondel** [comment]
Thanks for letting us know! We're working on fixing this.

**Comment by ptoonen** [comment]
We've had an issue with an expired token and a non-functioning alert (from both our end and letsencrypt's notification went to /dev/null too apparently). It's been fixed and we're taking further steps to prevent this.
