### ISSUE TITLE
Support flat square style for the mutation score badge

### ISSUE THREAD

**Issue by acelaya** [stryker-mutator/stryker-dashboard#99]
It would be nice to be able to change the badge style, similar to what https://shields.io does.

**Comment by simondel** [comment]
@nicojs Could you provide info on the new function you deployed?

**Comment by nicojs** [comment]
We're working on a new implementation that utilizes https://shields.io/endpoint. Stay tuned

**Comment by acelaya** [comment]
Nice! 😀
